# Crime Preprocessing Notebook

In [26]:
import pandas as pd
import os

##### Combining the raw_police_data Folder into a single DataFrame

In [27]:
# Assumes python is running from this notebook
# If your current directory is anything else change this to the relative path of the
# raw_police_data file
raw_police_data = f"{os.path.dirname(os.path.normpath(os.getcwd()))}/data/raw/raw_poilice_data"

In [56]:
# Assumes you want to save the output file in the processed folder.
# If not, change this to the relative path of the folder you wish to export the processed file to
processed_folder = f"{os.path.dirname(os.path.normpath(os.getcwd()))}/data/processed"

In [28]:
def parse_police_crime_data(base_folder):
    '''Parse the contents of base_folder into a dataframe and return that dataframe

    Using the os Python library we can loop through the folder to create a dataframe
    of all the csv files in the folder. This loop assumes that the raw_police_data's
    file structure has not been changed since it has been unzipped
    '''
    dataframes = []

    for folder in os.listdir(base_folder):
        folder_path = os.path.join(base_folder, folder)
        if os.path.isdir(folder_path):
            for file in os.listdir(folder_path):
                if file.endswith(".csv"):
                    file_path = os.path.join(folder_path, file)
                    df = pd.read_csv(file_path)
                    dataframes.append(df)
    
    return dataframes

In [29]:
raw_crime_df = parse_police_crime_data(raw_police_data)

In [30]:
crime_df = pd.concat(raw_crime_df, ignore_index=True)
crime_df.shape
crime_df.info()
crime_df.sample(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3321691 entries, 0 to 3321690
Data columns (total 12 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Crime ID               object
 1   Month                  object
 2   Reported by            object
 3   Falls within           object
 4   Longitude              float64
 5   Latitude               float64
 6   Location               object
 7   LSOA code              object
 8   LSOA name              object
 9   Crime type             object
 10  Last outcome category  object
 11  Context                float64
dtypes: float64(3), object(9)
memory usage: 304.1+ MB

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
2134868,0b35b08b4438b21367162b3b9b6dbdb76c665130376971...,2024-05,Metropolitan Police Service,Metropolitan Police Service,0.045951,51.577517,On or near Avondale Crescent,E01003675,Redbridge 036A,Vehicle crime,Investigation complete; no suspect identified,NaN
2131430,f758e2f73f77ef8b5bbca0ce1967f80e90c1aa7e98b63c...,2024-05,Metropolitan Police Service,Metropolitan Police Service,0.060580,51.512910,On or near Pearl Close,E01003486,Newham 033C,Criminal damage and arson,Investigation complete; no suspect identified,NaN
3113445,8665dba966d4d88f227d7de0ed6c4f1a26d2fe85ca86ea...,2024-12,Metropolitan Police Service,Metropolitan Police Service,0.185438,51.533140,On or near Danbury Road,E01002375,Havering 028E,Violence and sexual offences,Unable to prosecute suspect,NaN
3243369,3506379143d666b03e0a86e0611ab77b4637143dad649b...,2025-01,Metropolitan Police Service,Metropolitan Police Service,0.183508,51.575946,On or near Chandlers Way,E01002356,Havering 013C,Violence and sexual offences,Awaiting court outcome,NaN
349333,a129027047b933af7b73cdb8179d2f32f45a0a626476b0...,2023-04,Metropolitan Police Service,Metropolitan Police Service,-0.135435,51.511612,On or near Brewer Street,E01033595,Westminster 013E,Burglary,Investigation complete; no suspect identified,NaN
752653,72a92b34eccb4b3534fbc55455370db940556740b56b13...,2023-07,Metropolitan Police Service,Metropolitan Police Service,0.011345,51.549816,On or near Bramall Close,E01003549,Newham 006C,Vehicle crime,Investigation complete; no suspect identified,NaN
1839763,7b0ec025edbe40395b62766b6c26cf9180ce63f03def74...,2024-03,Metropolitan Police Service,Metropolitan Police Service,-0.206081,51.515250,On or near Kensington Park Mews,E01002833,Kensington and Chelsea 007A,Theft from the person,Investigation complete; no suspect identified,NaN
466816,2c47f9b2371f5a8a390eb5fc7120d9c1b363ab83884a4b...,2023-05,Metropolitan Police Service,Metropolitan Police Service,0.084791,51.551375,On or near Chertsey Road,E01003684,Redbridge 030B,Vehicle crime,Investigation complete; no suspect identified,NaN
1983551,913de12082bd133223e886bf1d8dc2b35c1d42ed5083b9...,2024-04,Metropolitan Police Service,Metropolitan Police Service,-0.006212,51.450701,On or near Supermarket,E01003292,Lewisham 017A,Shoplifting,Investigation complete; no suspect identified,NaN
352151,d59d4a907164e13347addd2648b7d7bea4698726cac202...,2023-04,Metropolitan Police Service,Metropolitan Police Service,-0.119880,51.513477,On or near,E01004735,Westminster 018B,Theft from the person,Investigation complete; no suspect identified,NaN

In [31]:
# Checking for nulls
crime_df.isnull().sum()

Crime ID                  612561
Month                          0
Reported by                    0
Falls within                   0
Longitude                  50961
Latitude                   50961
Location                       0
LSOA code                  50967
LSOA name                  50967
Crime type                     0
Last outcome category     612561
Context                  3321691
dtype: int64

In [32]:
crime_df['Crime ID'].value_counts().head()

Crime ID
ecb359b56b9099e37a824296ea35d1d00a8cfec4c5d325af150240cccbae5002    15
d90a3d0737a5d883fea4789a826f80b712d7e54e803c0645899303561e6e64f5    10
acd3a8b264e0325bc71d44b687e5b0bfc0811e2eb4c557003d7e0688c404ab7e    10
0a75e8e953205cb5d6574c853db7646fb6b78f2978d6915de8546c942d9109d6     9
79013f8885f94e71bd6efc1d7ea448251c5ccfe2a2eb0ba9c6425a0264658d9c     9
Name: count, dtype: int64

In [33]:
crime_df[crime_df['Crime ID'] == 'ecb359b56b9099e37a824296ea35d1d00a8cfec4c5d325af150240cccbae5002']

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
1484615,ecb359b56b9099e37a824296ea35d1d00a8cfec4c5d325...,2023-12,North Yorkshire Police,North Yorkshire Police,-1.178653,53.818086,On or near Oxmoor Lane,E01027888,Selby 002D,Other crime,Status update unavailable,NaN
1484616,ecb359b56b9099e37a824296ea35d1d00a8cfec4c5d325...,2023-12,North Yorkshire Police,North Yorkshire Police,-1.178653,53.818086,On or near Oxmoor Lane,E01027888,Selby 002D,Other crime,Status update unavailable,NaN
1484617,ecb359b56b9099e37a824296ea35d1d00a8cfec4c5d325...,2023-12,North Yorkshire Police,North Yorkshire Police,-1.178653,53.818086,On or near Oxmoor Lane,E01027888,Selby 002D,Other crime,Status update unavailable,NaN
1484618,ecb359b56b9099e37a824296ea35d1d00a8cfec4c5d325...,2023-12,North Yorkshire Police,North Yorkshire Police,-1.178653,53.818086,On or near Oxmoor Lane,E01027888,Selby 002D,Other crime,Status update unavailable,NaN
1484619,ecb359b56b9099e37a824296ea35d1d00a8cfec4c5d325...,2023-12,North Yorkshire Police,North Yorkshire Police,-1.178653,53.818086,On or near Oxmoor Lane,E01027888,Selby 002D,Other crime,Status update unavailable,NaN
1484620,ecb359b56b9099e37a824296ea35d1d00a8cfec4c5d325...,2023-12,North Yorkshire Police,North Yorkshire Police,-1.178653,53.818086,On or near Oxmoor Lane,E01027888,Selby 002D,Other crime,Investigation complete; no suspect identified,NaN
1484621,ecb359b56b9099e37a824296ea35d1d00a8cfec4c5d325...,2023-12,North Yorkshire Police,North Yorkshire Police,-1.178653,53.818086,On or near Oxmoor Lane,E01027888,Selby 002D,Other crime,Status update unavailable,NaN
1484622,ecb359b56b9099e37a824296ea35d1d00a8cfec4c5d325...,2023-12,North Yorkshire Police,North Yorkshire Police,-1.178653,53.818086,On or near Oxmoor Lane,E01027888,Selby 002D,Other crime,Status update unavailable,NaN
1484623,ecb359b56b9099e37a824296ea35d1d00a8cfec4c5d325...,2023-12,North Yorkshire Police,North Yorkshire Police,-1.178653,53.818086,On or near Oxmoor Lane,E01027888,Selby 002D,Other crime,Status update unavailable,NaN
1484624,ecb359b56b9099e37a824296ea35d1d00a8cfec4c5d325...,2023-12,North Yorkshire Police,North Yorkshire Police,-1.178653,53.818086,On or near Oxmoor Lane,E01027888,Selby 002D,Other crime,Status update unavailable,NaN
1484625,ecb359b56b9099e37a824296ea35d1d00a8cfec4c5d325...,2023-12,North Yorkshire Police,North Yorkshire Police,-1.178653,53.818086,On or near Oxmoor Lane,E01027888,Selby 002D,Other crime,Status update unavailable,NaN
1484626,ecb359b56b9099e37a824296ea35d1d00a8cfec4c5d325...,2023-12,North Yorkshire Police,North Yorkshire Police,-1.178653,53.818086,On or near Oxmoor Lane,E01027888,Selby 002D,Other crime,Status update unavailable,NaN
1484627,ecb359b56b9099e37a824296ea35d1d00a8cfec4c5d325...,2023-12,North Yorkshire Police,North Yorkshire Police,-1.178653,53.818086,On or near Oxmoor Lane,E01027888,Selby 002D,Other crime,Status update unavailable,NaN
1484628,ecb359b56b9099e37a824296ea35d1d00a8cfec4c5d325...,2023-12,North Yorkshire Police,North Yorkshire Police,-1.178653,53.818086,On or near Oxmoor Lane,E01027888,Selby 002D,Other crime,Status update unavailable,NaN
1484629,ecb359b56b9099e37a824296ea35d1d00a8cfec4c5d325...,2023-12,North Yorkshire Police,North Yorkshire Police,-1.178653,53.818086,On or near Oxmoor Lane,E01027888,Selby 002D,Other crime,Status update unavailable,NaN

### Observations

- Context column is an empty column, Not needed for the planned analysis as crimes can be categorised by crime type
- Crime ID has many empty records. It's hard to ensure if crimes have been duplicated across months. 
- Crime ID is supposed to be a unique one way hash key to the actual crime reference number but there are many duplicate Crime IDs, these records have identical information aside from changes to Outcome Category and Crime Type and will be treated as duplicate Crime IDs.
- Longtitude/Langtitude often missing likely due to gaps in reporting and, according to data.police.uk, excluded from the database to proetct the identity of victims. These rows cannot be used for any maps or hotspot analysis but are still useful for general crime totals.
- Last Outcome: Where there is no Crime ID there is no last outcome, set to "Unkown"

##### Addressing Null Values and Standardising Datatypes

In [34]:
crime_df.drop(columns=['Context'], inplace=True)

In [35]:
crime_df['Month'] = pd.to_datetime(crime_df['Month'], format='%Y-%m')

In [36]:
crime_df['Has_Coordinates'] = crime_df['Longitude'].notna() & crime_df["Latitude"].notna()
crime_df['Missing_Crime_ID'] = crime_df['Crime ID'].isna()
crime_df['No_Outcome'] = crime_df['Last outcome category'].isna()

In [37]:
crime_df.sample(5)

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Has_Coordinates,Missing_Crime_ID,No_Outcome
672725,76e108b89ee8867322cb6ce5bb13f110de26ec170bf13f...,2023-06-01,Thames Valley Police,Thames Valley Police,-0.598345,51.507986,On or near Moorstown Court,E01032730,Slough 009G,Other theft,Action to be taken by another organisation,True,False,False
993353,6b0d48e66642879f1a7b91275a9bd11320167ccdbc901e...,2023-09-01,Metropolitan Police Service,Metropolitan Police Service,-0.098212,51.614599,On or near Millicent Grove,E01001397,Enfield 035C,Violence and sexual offences,Investigation complete; no suspect identified,True,False,False
2026628,fca87dc70145373b3d5ae452ce999dd64e7b1e7931e944...,2024-04-01,South Wales Police,South Wales Police,-3.377367,51.746084,On or near John Street,W01001315,Merthyr Tydfil 004D,Shoplifting,Investigation complete; no suspect identified,True,False,False
139607,05bc8a032c983163f8202d439ec6921f39e3370db38a93...,2023-03-01,Metropolitan Police Service,Metropolitan Police Service,0.124424,51.440646,On or near Wakeford Close,E01000446,Bexley 024D,Other theft,Investigation complete; no suspect identified,True,False,False
2182042,7ceab92662a6c9c46308c9adcbbdd11f9f100e494d07c4...,2024-05-01,Thames Valley Police,Thames Valley Police,-0.665217,51.529313,On or near Burlington Road,E01017809,Buckinghamshire 066E,Criminal damage and arson,Investigation complete; no suspect identified,True,False,False

In [39]:
crime_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3321691 entries, 0 to 3321690
Data columns (total 14 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Crime ID               object
 1   Month                  datetime64[ns]
 2   Reported by            object
 3   Falls within           object
 4   Longitude              float64
 5   Latitude               float64
 6   Location               object
 7   LSOA code              object
 8   LSOA name              object
 9   Crime type             object
 10  Last outcome category  object
 11  Has_Coordinates        bool
 12  Missing_Crime_ID       bool
 13  No_Outcome             bool
dtypes: bool(3), datetime64[ns](1), float64(2), object(8)
memory usage: 288.3+ MB

##### Adressing Duplicates

In [38]:
BEFORE = len(crime_df)
print(BEFORE)

3321691

Since the duplicates share the same month and location, the most useful record is the most **up to date** and **complete** record, hence the following deduplication rules

1. Prefer rows with a non-null Last outcome category
2. Prefer rows with location information
3. Prefer the last recorded occurence of this Crime_ID

We also need to handle crimes without Crime_IDS differently. While it is difficult to verify the uniqueness of rows with no Crime_IDs, its important to not completely discard them as there are reported and recorded crime occurences. We will use gross row deduplication as all of the crimes recorded without Crime IDs are [Anti-Social Behaviour (ASB)](https://www.met.police.uk/advice/advice-and-information/asb/asb/antisocial-behaviour/what-is-antisocial-behaviour/) reports and are not typically reported by Police Forces with a last outcome category.

In [ ]:
# Dividing the dataframe based on crimes with and without datatypes
with_id = crime_df[~crime_df['Missing_Crime_ID']]
without_id = crime_df[crime_df['Missing_Crime_ID']]

In [41]:
with_id.head(3)

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Has_Coordinates,Missing_Crime_ID,No_Outcome
0,f0328106bc02e93427dce3eb53d6f3c7afa026c49201a8...,2023-02-01,Devon & Cornwall Police,Devon & Cornwall Police,-0.144541,51.608066,On or near Pert Close,E01000163,Barnet 022C,Violence and sexual offences,Unable to prosecute suspect,True,False,False
1,e6ba2c24878867d6038f592e03d7b8c4d78d3ac985ef4b...,2023-02-01,Devon & Cornwall Police,Devon & Cornwall Police,0.644475,52.607173,On or near Pine Avenue,E01026444,Breckland 012B,Other theft,Investigation complete; no suspect identified,True,False,False
2,eff5207105724af3b3f001e2cdac3556ca65a48d743764...,2023-02-01,Devon & Cornwall Police,Devon & Cornwall Police,-1.425469,53.268124,On or near The Glebe Way,E01019574,Chesterfield 001E,Violence and sexual offences,Unable to prosecute suspect,True,False,False

In [42]:
without_id.head(3)

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Has_Coordinates,Missing_Crime_ID,No_Outcome
6,NaN,2023-02-01,Devon & Cornwall Police,Devon & Cornwall Police,-4.544115,50.827946,On or near The Strand,E01018936,Cornwall 001A,Anti-social behaviour,NaN,True,True,True
15,NaN,2023-02-01,Devon & Cornwall Police,Devon & Cornwall Police,-4.532641,50.829266,On or near Primrose Road,E01018937,Cornwall 001B,Anti-social behaviour,NaN,True,True,True
36,NaN,2023-02-01,Devon & Cornwall Police,Devon & Cornwall Police,-4.539779,50.767932,On or near Bangors Estate,E01018951,Cornwall 002B,Anti-social behaviour,NaN,True,True,True

In [45]:
# All crimes recorded without IDs are anti-social behaviour reports
without_id['Crime type'].value_counts()

Crime type
Anti-social behaviour    612561
Name: count, dtype: int64

In [43]:
## How many unique crime IDs appear more than once.
duplicate_ids = with_id['Crime ID'].value_counts()
duplicate_ids = duplicate_ids[duplicate_ids > 1]

print(len(duplicate_ids))

35421

In [ ]:
with_id = with_id.sort_values(
    ['Crime ID', 'No_Outcome', 'Has_Coordinates'],
    ascending=[True, False, True]
)

with_id.drop_duplicates(subset=["Crime ID"], keep='last', inplace=True)

In [48]:
without_id = without_id.sort_values(['Crime ID', 'Has_Coordinates'])
without_id.drop_duplicates(keep='last', inplace=True)

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Has_Coordinates,Missing_Crime_ID,No_Outcome
96680,NaN,2023-02-01,North Yorkshire Police,North Yorkshire Police,NaN,NaN,No Location,NaN,NaN,Anti-social behaviour,NaN,False,True,True
106876,NaN,2023-02-01,South Wales Police,South Wales Police,NaN,NaN,No Location,NaN,NaN,Anti-social behaviour,NaN,False,True,True
123225,NaN,2023-02-01,Thames Valley Police,Thames Valley Police,NaN,NaN,No Location,NaN,NaN,Anti-social behaviour,NaN,False,True,True
231634,NaN,2023-03-01,North Yorkshire Police,North Yorkshire Police,NaN,NaN,No Location,NaN,NaN,Anti-social behaviour,NaN,False,True,True
242825,NaN,2023-03-01,South Wales Police,South Wales Police,NaN,NaN,No Location,NaN,NaN,Anti-social behaviour,NaN,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3321286,NaN,2025-01-01,Thames Valley Police,Thames Valley Police,-0.858614,51.359976,On or near Longwater Road,E01016640,Wokingham 019F,Anti-social behaviour,NaN,True,True,True
3321295,NaN,2025-01-01,Thames Valley Police,Thames Valley Police,-0.800196,51.382124,On or near Duchess Close,E01016705,Wokingham 020A,Anti-social behaviour,NaN,True,True,True
3321301,NaN,2025-01-01,Thames Valley Police,Thames Valley Police,-0.796977,51.382163,On or near Lupin Ride,E01016706,Wokingham 020B,Anti-social behaviour,NaN,True,True,True
3321304,NaN,2025-01-01,Thames Valley Police,Thames Valley Police,-0.804458,51.375766,On or near New Wokingham Road,E01016709,Wokingham 020E,Anti-social behaviour,NaN,True,True,True
3321305,NaN,2025-01-01,Thames Valley Police,Thames Valley Police,-0.800300,51.375957,On or near Butler Road,E01016709,Wokingham 020E,Anti-social behaviour,NaN,True,True,True

In [51]:
crime_df = pd.concat([with_id, without_id])

In [52]:
crime_df['Crime ID'].value_counts().head()

Crime ID
fffffd9f30997a094fbc1fd4d27e2b1eca004a44e4194a251a5fc289ddbde148    1
0000091b5d32af02f1538cccd3b3f537c199ba083993c6b36d5c5f1293d2646d    1
00001339d3385ca3f12a6870669eba5922853f74ec2c16a48bdf8bdfd9df2ffb    1
0000184b7a2fe83e5827a71e13479a8aa87f25b3d6709ef281e4d7681bf9780e    1
000019878b0f70df52cf68253c60f94f5d97bad7123566cffcdc79b98209c86b    1
Name: count, dtype: int64

##### Adding Analysis Years to be used during analysis

The ONS mid-year estimates are point-in-time snapshots (mid-June each year), and for the purpose of this analysis using mid-2023 for Year 1 (data from Feb 2023 - Jan 2024) and mid-2024 for Year 2 (data from Feb 2024 - Jan 2025)

In [ ]:
def assign_year(month):
    '''Assings an analysis year to records based on the Month the crime occurred'''
    if pd.Timestamp('2023-02-01') <= month <= pd.Timestamp('2024-01-31'):
        return 'Year 1'
    elif pd.Timestamp('2024-02-01') <= month <= pd.Timestamp('2025-01-31'):
        return 'Year 2'

crime_df['analysis_year'] = crime_df['Month'].apply(assign_year)

##### Exporting to csvs for analysis

In [59]:
# Data Quality Checks
crime_df.shape
crime_df.info()
crime_df.sample(5)

<class 'pandas.core.frame.DataFrame'>
Index: 3281512 entries, 1798768 to 3321305
Data columns (total 15 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Crime ID               object
 1   Month                  datetime64[ns]
 2   Reported by            object
 3   Falls within           object
 4   Longitude              float64
 5   Latitude               float64
 6   Location               object
 7   LSOA code              object
 8   LSOA name              object
 9   Crime type             object
 10  Last outcome category  object
 11  Has_Coordinates        bool
 12  Missing_Crime_ID       bool
 13  No_Outcome             bool
 14  analysis_year          object
dtypes: bool(3), datetime64[ns](1), float64(2), object(9)
memory usage: 334.9+ MB

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Has_Coordinates,Missing_Crime_ID,No_Outcome,analysis_year
2161161,1295aead5eccee7e175088548df0e56a76739c5c0e9034...,2024-05-01,North Yorkshire Police,North Yorkshire Police,-1.560805,53.989056,On or near Sussex Avenue,E01027652,Harrogate 015A,Violence and sexual offences,Unable to prosecute suspect,True,False,False,Year 2
1456738,23d5afa4065ad0b3e6177a32c5d038e24bc9f69145d18e...,2023-12-01,Metropolitan Police Service,Metropolitan Police Service,-0.091679,51.503391,On or near Borough High Street,E01003929,Southwark 002B,Violence and sexual offences,Investigation complete; no suspect identified,True,False,False,Year 1
1290496,fd8020874c34c0df16a839b4e97c0761a6998596fd52b2...,2023-11-01,Metropolitan Police Service,Metropolitan Police Service,0.190725,51.574463,On or near Bury Mews,E01002358,Havering 016E,Vehicle crime,Investigation complete; no suspect identified,True,False,False,Year 1
1206318,ff730fdd07006e321ad0b8714b9601fadef19c71320cf9...,2023-10-01,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Violence and sexual offences,Investigation complete; no suspect identified,False,False,False,Year 1
3079365,e684472968969b2854f2ef488d4ce63bd7f5847b6b2139...,2024-12-01,Metropolitan Police Service,Metropolitan Police Service,0.149110,51.457048,On or near Police Station,E01000330,Bexley 017D,Public order,Court result unavailable,True,False,False,Year 2

In [60]:
print('Total records:', len(crime_df))
print('Missing crime IDs:', crime_df['Missing_Crime_ID'].sum())
print('Missing coordinates:', (~crime_df['Has_Coordinates']).sum())
print('Missing outcomes:', crime_df['No_Outcome'].sum())

Total records: 3281512
Missing crime IDs: 612561
Missing coordinates: 50077
Missing outcomes: 612561

In [61]:
AFTER = len(crime_df)
print(AFTER)
print(f"Rows Removed {BEFORE - AFTER}")

3281512
Rows Removed 40179

In [62]:
crime_df.to_csv(f"{processed_folder}/crime_master.csv", index=False)